### ISSUE TITLE
您好，关于 LaSOT，TrackingNet，GOT10K and COCO 4个通用 +  AntiUAV600 training set 这训练时 DATASETS_RATIO 和SAMPLE_PER_EPOCH的问题。

### ISSUE THREAD

**Issue by NewboySoCool** [xuefeng-zhu5/EDTC#8]
您好，感谢您出色的工作，我有些问题关于跟踪网络训练时。 
```
 DATASETS_NAME:
    - GOT10K_vottrain
    - LASOT
    - COCO17
    - TRACKINGNET
    - AntiUAV_train
    DATASETS_RATIO:
    - 1
    - 1
    - 1
    - 1
    - 1
    SAMPLE_PER_EPOCH: 60000
```
这个DATASETS_RATIO 都是需要给1 ？ SAMPLE_PER_EPOCH给6w?   
或者说 我如果想要把Anti-UAV410的数据加入进去，配置应该改成下面？  AntiUAV_train410比例也是1，SAMPLE_PER_EPOCH仍是6w?
```
 DATASETS_NAME:
    - GOT10K_vottrain
    - LASOT
    - COCO17
    - TRACKINGNET
    - AntiUAV_train
    - AntiUAV_train410
    DATASETS_RATIO:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 1
    SAMPLE_PER_EPOCH: 60000
```
